[package]
name = "ap-project"
version = "0.1.0"
edition = "2021"

[dependencies]
wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git", features = ["serialize"] }
toml = "0.8.19"
crossbeam = "0.8.4"
d-r-o-n-e_drone = { git = "file:///Users/mattia/Desktop/drone/drone/", branch = "logging-system" }
