[package]
name = "ap-project"
version = "0.1.0"
edition = "2021"

[dependencies]
wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git", features = ["serialize"] }
toml = "0.8.19"
crossbeam = "0.8.4"
d-r-o-n-e_drone = { git = "https://github.com/AP-2024-25-D-R-O-N-E/drone.git" }
simple_logger = "5.0.0"
log = "0.4.22"
colored = "2.1.0"
egui_graphs = { git = "https://github.com/mattia-marini/egui_graphs.git", features = ["events"] }
egui = "0.29"
eframe = "0.29"
serde_json = "1.0"
petgraph = "0.6"
fdg = { git = "https://github.com/grantshandy/fdg" }
rand = "0.8"
