[package]
name = "ap-project"
version = "0.1.0"
edition = "2021"

[dependencies]
wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git", features = ["serialize"] }
toml = "0.8.19"
crossbeam = "0.8.4"
simple_logger = "5.0.0"
log = "0.4.22"
colored = "2.1.0"
egui_graphs = { version = "0.22.0", features = ["events"] }
egui = "0.29"
eframe = "0.29"
serde_json = "1.0"
petgraph = "0.6"
fdg = { git = "https://github.com/grantshandy/fdg" }
rand = "0.8"
d-r-o-n-e_drone = { git = "https://github.com/AP-2024-25-D-R-O-N-E/drone.git", branch = "flooding-path-trace-fix" }
rustafarian-drone = { git = "https://github.com/Rustafarian-Unitn/rustafarian-drone"}
lockheedrustin-drone = { git = "https://github.com/Lockheed-Rustin/drone.git" }
rusty_drones = { git = "https://github.com/matteo-dinoia/rusty-drones", branch = "main" }
rustbusters-drone = { git = "https://github.com/Rustbusters/drone.git" }
# ap2024_unitn_cppenjoyers_drone = { git = "https://github.com/Cpp-enjoyers/drone.git" }
rusteze_drone = { git = "https://github.com/Rusteze-AP/drone.git", branch = "main" }