[[drone]]
id = 0
connected_drone_ids = [1, 2]
pdr = 0.05

[[drone]]
id = 1
connected_drone_ids = [0,2]
pdr = 0.03

[[drone]]
id = 2
connected_drone_ids = [1,0]
pdr = 0.14

[[client]]
id = 3
connected_drone_ids = [3, 2]

[[client]]
id = 4
connected_drone_ids = [1]

[[server]]
id = 5
connected_drone_ids = [2,3]